language: python
python:
    - '3.8'

services:
    - docker

addons:
    ssh_known_hosts: ssh.pythonanywhere.com

before_install:
    openssl aes-256-cbc -K $encrypted_4cefc8a5b2ff_key -iv $encrypted_4cefc8a5b2ff_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

install:
    - pip install -r docker/requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/gcallah/OnlineDevops

script:
    - make tests

after_success:
    - ./deploy.sh

notifications:
  slack: devopsnyu:vAFcJBgAP2f73SqhWgb40Gjf
