# Generated by Django 2.1 on 2018-08-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=256)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('qtype', models.CharField(choices=[('MCHOICE', 'Multiple choice'), ('TF', 'True/False'), ('BLANK', 'Fill-in-the-blank'), ('ESSAY', 'Essay')], max_length=10)),
                ('correct', models.CharField(max_length=1)),
                ('answerA', models.CharField(blank=True, max_length=128, null=True)),
                ('answerB', models.CharField(blank=True, max_length=128, null=True)),
                ('answerC', models.CharField(blank=True, max_length=128, null=True)),
                ('answerD', models.CharField(blank=True, max_length=128, null=True)),
                ('answerE', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=16)),
                ('minpass', models.FloatField(default=80.0)),
                ('numq', models.IntegerField()),
            ],
        ),
    ]
