# Generated by Django 2.1.2 on 2019-04-24 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_order', models.IntegerField(blank=True, null=True)),
                ('module', models.CharField(max_length=16, unique=True)),
                ('title', models.TextField()),
                ('next_module', models.CharField(max_length=16)),
                ('content', tinymce.models.HTMLField(default='Please enter your contents here!')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', tinymce.models.HTMLField(default='Please enter your contents here!')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('quiz_name', models.CharField(default='work', max_length=16)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('order', models.IntegerField(unique=True)),
                ('lesson_order', models.IntegerField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(default='Please enter your contents here!')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.CourseModule')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=256)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('qtype', models.CharField(choices=[('MCHOICE', 'Multiple choice'), ('TF', 'True/False'), ('BLANK', 'Fill-in-the-blank'), ('ESSAY', 'Essay')], max_length=10)),
                ('correct', models.CharField(max_length=1)),
                ('answerA', models.CharField(blank=True, max_length=128, null=True)),
                ('answerB', models.CharField(blank=True, max_length=128, null=True)),
                ('answerC', models.CharField(blank=True, max_length=128, null=True)),
                ('answerD', models.CharField(blank=True, max_length=128, null=True)),
                ('answerE', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=16, unique=True)),
                ('minpass', models.FloatField(default=80.0)),
                ('numq', models.IntegerField()),
                ('show_answers', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quiz', to='devops.Quiz'),
        ),
    ]
