# Generated by Django 2.1.1 on 2019-04-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_extras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
