# Generated by Django 2.1.1 on 2018-09-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='quiz_name',
            field=models.CharField(default='work', max_length=16),
        ),
    ]
