# Generated by Django 2.1.2 on 2019-09-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0004_auto_20190503_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['module']},
        ),
    ]
