# Generated by Django 2.1.1 on 2018-10-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0004_auto_20180917_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=16)),
                ('title', models.TextField()),
                ('next_module', models.CharField(max_length=16)),
            ],
        ),
    ]
