# Generated by Django 2.1.1 on 2018-10-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0005_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='CourseModule',
        ),
    ]
