# Generated by Django 2.1 on 2018-11-17 19:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0007_quiz_show_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='content',
            field=tinymce.models.HTMLField(default='Please transfer your content here!'),
        ),
    ]
