# Generated by Django 2.1 on 2018-12-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0008_coursemodule_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='module',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
