# Generated by Django 2.1.1 on 2019-04-08 17:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0009_auto_20181209_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('order', models.IntegerField(unique=True)),
                ('content', tinymce.models.HTMLField(default='Please enter your contents here!')),
            ],
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='content',
            field=tinymce.models.HTMLField(default='Please enter your contents here!'),
        ),
        migrations.AddField(
            model_name='modulesection',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.CourseModule'),
        ),
    ]
