# Generated by Django 2.1.2 on 2019-04-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0010_auto_20190408_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesection',
            name='lesson_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
