# Generated by Django 2.1.2 on 2019-04-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0010_auto_20190408_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesection',
            name='lesson_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulesection',
            name='order',
            field=models.IntegerField(),
        ),
    ]
