# Generated by Django 2.1.2 on 2019-04-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0011_auto_20190420_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='course_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulesection',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
