# Generated by Django 2.1.2 on 2019-04-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0011_modulesection_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='course_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
