# Generated by Django 2.1.2 on 2019-04-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0013_extras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extras',
            new_name='Extra',
        ),
    ]
