# Generated by Django 2.1.2 on 2019-04-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0014_auto_20190423_1827'),
        ('devops', '0012_coursemodule_course_order'),
    ]

    operations = [
    ]
