# This is a basic workflow to help you get started with Actions

name: PythonAnywhere deployment

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive


        # - name: Establish OpenSSL connection
        # run: openssl aes-256-cbc -K $encrypted_4cefc8a5b2ff_key -iv $encrypted_4cefc8a5b2ff_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
        
      - name: Install the development requirements
        run: pip install -r requirements-dev.txt
        
      - name: Run the tests
        run: |
          PYTHONPATH=/home/runner/work/OnlineDevops/OnlineDevops
          make tests
          
      - name: Deploy the project to PythonAnywhere
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SECRET_KEY }}
          known_hosts: 'devopscourse@ssh.pythonanywhere.com'
          run: |
            ls